app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('usuarios.urls')),
    path('xlsmaker/', include('xlsmaker.urls')),
    path('admin/', admin.site.urls),
     
   
]

usuarios/urls.py
from django.urls import path
from .import views
app_name = 'usuarios' 
urlpatterns = [
    path('', views.login_view, name='user_login' ),
    path('register/', views.register_view, name='register' ),    
    path('plataforma', views.plataforma, name='plataforma'),
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('solicitacoes/delete/<int:id>/', views.delete_solicitacao, name='delete_solicitacao'),
    path('usuarios', views.listar_usuarios, name='listar_usuarios'),
    path('create/users', views.create_users_view, name='criar_usuarios' ),
    path('update-user-status/', views.update_user_status, name='update_user_status'),
    path('update-user-tokens/', views.update_user_tokens, name='update_user_tokens'),
    path('editar/<int:id>/', views.editar_usuario, name='editar_usuario'),
    path('editar/tokens/<int:id>/', views.editar_tokens, name='editar_tokens'),    
    path('deletar/<int:id>/', views.deletar_usuario, name='deletar_usuario'),
    path('deletar/tokens/<int:id>/', views.deletar_tokens, name='deletar_tokens'),    
    path('dismiss-tutorial/', views.dismiss_tutorial, name='dismiss-tutorial'),
    path('tokens', views.listar_tokens, name='listar_tokens'),
    
]

usuarios/models.py
from django.db import models

usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from xlsmaker.models import Solicitacao 
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
import json
import requests
from xlsmaker.models import UserProfile 
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.db.models import Q


# Função auxiliar para verificar se é admin
def is_admin(user):
    return user.is_authenticated and (user.is_staff or user.is_superuser)

def register_view(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirma_password = request.POST.get('confirma_password')

        if password != confirma_password:
            messages.error(request, 'As senhas não coincidem!')
            return render(request, 'register.html', {'username': username, 'email': email})
        
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Nome de usuário já está em uso!')
            return render(request, 'register.html', {'email': email})
        
        try:
            user = User.objects.create_user(username=username, email=email, password=password)
            user.is_active = False
            user.save()
            messages.success(request, 'Cadastro realizado com sucesso! Faça seu login.')
            return redirect('usuarios:user_login')
        except Exception as e:
            messages.error(request, f'Erro ao criar usuário: {str(e)}')
            return render(request, 'register.html')


def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        username = request.POST.get('username').strip()
        password = request.POST.get('password').strip()
        user = authenticate(username=username, password=password)
        
        if user is not None:
            if not user.is_active:
                messages.error(request, '❌ Sua conta está desativada. Entre em contato com o suporte.')
                return render(request, 'login.html')
            # Resetar tutorial para novos logins
            request.session['show_tutorial'] = True
            request.session['tutorial_dismissed'] = False  
         
            login(request, user)
            if is_admin(user):
                return redirect('usuarios:admin_dashboard')
            else:
                # Criar um perfil automaticamente se ainda não existir
                user_profile, created = UserProfile.objects.get_or_create(user=user, defaults={'tokens_atribuidos': 1000, 'tokens_gastos': 0})         
                return redirect('xlsmaker:dashboard') 
        else:
            messages.error(request, '❌ Erro: email ou senha inválidos!')
            return render(request, 'login.html')

@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Logout realizado com sucesso!')
    return redirect('login')

# Painéis de controle
@login_required
def user_dashboard(request):
    context = {'user': request.user}
    return render(request, 'dashboard/user.html', context)

@login_required
@user_passes_test(is_admin, login_url='/auth/login/')
def admin_dashboard(request):    
    query = request.GET.get('q', '')
    solicitacoes_list = Solicitacao.objects.all().order_by('-created_at')
    if query:
        solicitacoes_list = solicitacoes_list.filter(
            Q(nome__icontains=query) | Q(email__icontains=query) | Q(created_at__icontains=query)
        )
    paginator = Paginator(solicitacoes_list, 10)    
    page_number = request.GET.get('page') 
    solicitacoes = paginator.get_page(page_number)     
    context = {'solicitacoes': solicitacoes} 
      # Se for uma requisição AJAX, retorna o HTML parcial
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_users_solicitacoes.html', context)
        return JsonResponse({'html': html})
    return render(request, 'dashboard/admin.html', context)


# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_usuarios(request):
#     usuarios_list = User.objects.all().order_by('-date_joined') 
#     paginator = Paginator(usuarios_list, 10)    
#     page_number = request.GET.get('page')  
#     usuarios = paginator.get_page(page_number) 
#     context = {'usuarios': usuarios}
#     return render(request, 'dashboard/list_users.html', context)

@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def listar_usuarios(request):
    query = request.GET.get('q', '')
    usuarios_list = User.objects.all().order_by('-date_joined')

    if query:
        usuarios_list = usuarios_list.filter(
            Q(username__icontains=query) | Q(email__icontains=query)
        )

    paginator = Paginator(usuarios_list, 10)
    page_number = request.GET.get('page')
    usuarios = paginator.get_page(page_number)

    # Se for uma requisição AJAX, retorna o HTML parcial
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_users_table.html', {'usuarios': usuarios})
        return JsonResponse({'html': html})

    return render(request, 'dashboard/list_users.html', {'usuarios': usuarios})

# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_tokens(request):
#     query = request.GET.get('q', '')
#     user_profile_list = UserProfile.objects.select_related('user').all()
#     if query:
#       user_profile_list = user_profile_list.filter(
#             Q(user__username__icontains=query) | Q(user__email__icontains=query)
#     )
#     for profile in user_profile_list:
#         profile.saldo_tokens = profile.tokens_atribuidos - profile.tokens_gastos
#     paginator = Paginator(user_profile_list, 10)    
#     page_number = request.GET.get('page')  
#     user_profile = paginator.get_page(page_number) 
#     context = {'user_profile': user_profile}
    
#      # Se for uma requisição AJAX, retorna o HTML parcial
#     if request.headers.get('x-requested-with') == 'XMLHttpRequest':
#         html = render_to_string('dashboard/partials/_users_tokens.html', context)
#         return JsonResponse({'html': html})
    
#     return render(request, 'dashboard/list_tokens.html', context)
# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_tokens(request):

#     query = request.GET.get('q', '')
#     user_profile_list = UserProfile.objects.select_related('user').all()

#     if query:
#         user_profile_list = user_profile_list.filter(
#             Q(user__username__icontains=query) |
#             Q(user__email__icontains=query) |
#             Q(tokens_atribuidos__icontains=query)            
#         )

#     # Calcula saldo_tokens dinamicamente
#     for profile in user_profile_list:
#         profile.saldo_tokens = profile.tokens_atribuidos - profile.tokens_gastos

#     paginator = Paginator(user_profile_list, 10)
#     page_number = request.GET.get('page')
#     user_profile = paginator.get_page(page_number)

#     context = {'user_profile': user_profile}

#     if request.headers.get('x-requested-with') == 'XMLHttpRequest':
#         html = render_to_string('dashboard/partials/_users_tokens.html', context)
#         return JsonResponse({'html': html})

#     return render(request, 'dashboard/list_tokens.html', context)

@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def listar_tokens(request):
    query = request.GET.get('q', '')
    user_profile_list = UserProfile.objects.select_related('user').all().order_by('user__username')

    if query:
        # Filtra por texto (username ou email) OU por número exato de tokens
        try:
            query_as_int = int(query)
            user_profile_list = user_profile_list.filter(
                Q(user__username__icontains=query) |
                Q(user__email__icontains=query) |
                Q(tokens_atribuidos=query_as_int)
            )
        except ValueError:
            # Se não for um número, filtra apenas por texto
            user_profile_list = user_profile_list.filter(
                Q(user__username__icontains=query) |
                Q(user__email__icontains=query)
            )

    paginator = Paginator(user_profile_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'user_profile': page_obj,
        'query': query  # Passa a query para manter na paginação
    }

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_user_tokens.html', context)
        return JsonResponse({
            'html': html
        })

    return render(request, 'dashboard/list_tokens.html', context)


@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def create_users_view(request):
    if request.method == 'GET':
        return render(request, 'dashboard/create.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirma_password = request.POST.get('confirma_password')

        if password != confirma_password:

usuarios/templates/dashboard/create.html
{% extends "base.html" %}
{% block title %}ExpertAI{% endblock title %}
{% block content %}

 <main class="flex-1 p-8 bg-gray-100 min-h-screen overflow-x-auto mt-5">

                                 
      <div class="mb-4">                         
        <div  class="overflow-x-auto my-6 bg-gray-50 px-8 py-8 shadow-xl rounded-sm ring-1 ring-gray-200">
        <form class="space-y-6" action="{% url 'usuarios:criar_usuarios' %}" method="POST">
              {% csrf_token %}
          <div>
            <label for="email" class="block text-sm/6 font-medium text-gray-900"
              >Username</label
            >
            <div class="mt-2">           
              <input
                type="text"
                id="username"
                name="username"
                required
                class="w-full px-3 py-2 bg-gray-50 border border-gray-300 focus:border-emerald-500 focus:ring-3 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Digite o username" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o username'"
              />
            </div>
          </div>

           <div>
            <label for="email" class="block text-sm/6 font-medium text-gray-900"
              >Email</label
            >
            <div class="mt-2">           
              <input
                type="email"
                id="email"
                name="email"
                required
                class="w-full bg-gray-50 px-3 py-2 border border-gray-300 focus:border-emerald-500 focus:ring-3 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Digite o email" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o email'"
              />
            </div>
          </div>       

          <div>
               <label for="password" class="block text-sm/6 font-medium text-gray-900"
              >Password</label
            >
                    
            <div class="mt-2 relative">
              <input
                type="password"
                id="password"
                name="password"
                required
                class="w-full bg-gray-50 px-3 py-2 border border-gray-300 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300 pr-10"
                placeholder="Digite o password"
                onfocus="this.placeholder=''" onblur="this.placeholder='Digite o password'"
              />
              <button
                type="button"
                onclick="togglePassword()"
                class="absolute inset-y-0 right-2 flex items-center text-gray-500 hover:text-emerald-600"
                tabindex="-1"
              >
                <svg id="eyeIcon" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg>
              </button>
            </div>
          </div>
            <div>
               <label for="confirma_password" class="block text-sm/6 font-medium text-gray-900"
              >Confirma password</label
            >
                    
            <div class="mt-2 relative">
              <input
                type="password"
                id="confirma_password"
                name="confirma_password"
                required
                class="w-full bg-gray-50 px-3 py-2 border border-gray-300 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300 pr-10"
                placeholder="Confirma o password"
                onfocus="this.placeholder=''" onblur="this.placeholder='Confirma o password'"
              />
              <button
                type="button"
                onclick="toggleConfirmaPassword()"
                class="absolute inset-y-0 right-2 flex items-center text-gray-500 hover:text-emerald-600"
                tabindex="-1"
              >
                <svg id="confirmaEyeIcon" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none"
                  viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                </svg>
              </button>
            </div>
          </div>

          <div  class="flex justify-end">    
            <button
              type="reset"
              class="px-4 py-2 text-white bg-red-500 rounded hover:bg-red-700 focus:outline-none group flex items-center"
            >
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="currentColor">
                <path d="M13 3a9 9 0 1 0 6.36 15.36l-1.41-1.41A7 7 0 1 1 13 5v4l5-5-5-5v4z"/>
            </svg>
              Reset
            </button>&nbsp;        
            <button
              type="submit"
              class="px-4 py-2 text-white bg-emerald-500 rounded hover:bg-emerald-700 focus:outline-none group flex items-center"
            >
             <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" fill="currentColor">
                <path d="M3 3v18h18V7.83L16.17 3H3zm16 16H5V5h10v4h4v10zm-6-7h-4v6h4v-6zm-2-7c-.83 0-1.5.67-1.5 1.5S10.17 7 11 7s1.5-.67 1.5-1.5S11.83 3 11 3z"/>
            </svg>
              Save
            </button>
          </div>
        </form>
         </div>
      
                
    </div>               
            
</main>

{% endblock content %}

usuarios/templates/dashboard/list_tokens.html
{% extends "base.html" %}
{% block title %}ExpertAI{% endblock title %}
{% block content %}

 <main class="flex-1 p-8 bg-gray-100 min-h-screen overflow-x-auto mt-5">
    <div class="container mx-auto p-6">
    {% comment %} <div class="bg-gray-50 p-6 shadow rounded-md mb-6 mt-5">         {% endcomment %}
                             
      <div class="mb-4">                         
        <div class="overflow-x-auto rounded-md shadow-md border border-gray-300 my-6">
             <h1 class="font-normal my-4 ml-2 group flex items-center text-sm">
                 <svg class="w-4 h-4 mr-2 text-gray-700 group-hover:text-black" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M4 6h16M4 12h16M4 18h16"/>
                </svg>
                Gestão de tokens
             </h1> 
             <input
             type="text"
             id="searchInputToken"
             placeholder="Buscar por nome ou email"
              class="ml-2 mb-3 w-1/4 bg-gray-50 px-3 py-2 border border-gray-300 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
             />   
            <table class="w-full">
                <thead class="bg-emerald-500 text-white">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider">Username</th>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider">Email</th>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider ">Tokens Atribuídos</th>
                        <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ">Tokens Gastos</th>
                        <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ">Tokens disponíveis</th>
                        <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ">Reset</th>
                        <th class="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider "></th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% for profile in user_profile %}
                    <tr class="even:bg-gray-50 hover:bg-gray-100 transition-colors">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ profile.user.username}}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ profile.user.email }}</td>  
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ profile.tokens_atribuidos }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ profile.tokens_gastos }}</td> 
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ profile.saldo_tokens }}</td>                                       
                        <td class="px-6 py-2 whitespace-nowrap text-sm font-medium text-gray-500 text-left">
                            <select onchange="resetTokens({{ profile.id }}, this.value)" class="px-3 py-2 border border-gray-300 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300">
                                <option value="">Seleciona</option>
                                <option value="0">Reset</option>
                            </select>
                        </td>
                        <td class="px-6 py-2 whitespace-nowrap text-sm font-medium text-gray-500 text-right">
                            <select onchange="handleTokensAction({{ profile.id }}, this.value)" class="px-3 py-2 border border-gray-300 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300">
                                <option value="">Seleciona uma ação</option>
                                 <option value="{% url 'usuarios:editar_tokens' profile.id %}">Reatribuir</option>
                                 <option value="{% url 'usuarios:deletar_tokens' profile.id %}">Excluir</option>
                            </select>
                        </td> 
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="py-2 px-4 border text-center">Nenhum usuário cadastrado</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
             <div class="my-4 mx-2 flex justify-between items-center">
                    <span class="text-gray-600 text-sm">
                        Página {{ user_profile.number }} de {{ user_profile.paginator.num_pages }}
                    </span>

                    <div class="flex space-x-2">
                        {% if user_profile.has_previous %}
                            <a href="?page=1" class="px-3 py-1 bg-gray-200 rounded">⏮️ Primeira</a>
                            <a href="?page={{ user_profile.previous_page_number }}" class="px-3 py-1 bg-gray-200 rounded">⬅️ Anterior</a>
                        {% endif %}

                        {% if user_profile.has_next %}
                            <a href="?page={{ user_profile.next_page_number }}" class="px-3 py-1 bg-gray-200 rounded">Próxima ➡️</a>
                            <a href="?page={{ user_profile.paginator.num_pages }}" class="px-3 py-1 bg-gray-200 rounded">Última ⏭️</a>
                        {% endif %}
                    </div>
                </div>
         </div>
        {% comment %} </div> {% endcomment %}
                
    </div>               
 </div>       
</main>

{% endblock content %}

usuarios/templates/dashboard/list_users.html
{% extends "base.html" %}
{% block title %}ExpertAI{% endblock title %}
{% block content %}

 <main class="flex-1 p-8 bg-gray-100 min-h-screen overflow-x-auto mt-5">
    <div class="container mx-auto p-6">
    {% comment %} <div class="bg-gray-50 p-6 shadow rounded-md mb-6 mt-5">         {% endcomment %}
                             
      <div class="mb-4">                         
        <div class="overflow-x-auto rounded-lg shadow-md border border-gray-300 my-6">
             <h1 class="font-normal my-4 ml-2 group flex items-center text-sm">
                 <svg class="w-4 h-4 mr-2 text-gray-700 group-hover:text-black" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M4 6h16M4 12h16M4 18h16"/>
                </svg>
                Lista de Usuários
             </h1>    
             <input
                type="text"
                id="searchInput"
                placeholder="Buscar por nome ou email"
                 class="ml-2 mb-3 w-1/4 bg-gray-50 px-3 py-2 border border-gray-300 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                />

            <table class="w-full">
                <thead class="bg-emerald-500 text-white">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider">Username</th>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider">Email</th>
                        <th class="px-6 py-3 text-left text-xs font-medium  uppercase tracking-wider ">Status da conta</th>
                        <th class="px-6 py-3 text-right text-xs font-medium uppercase tracking-wider "></th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    {% for usuario in usuarios %}
                    <tr class="even:bg-gray-50 hover:bg-gray-100 transition-colors">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ usuario.username }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-500">{{ usuario.email }}</td>                       
                        <td class="px-6 py-2 whitespace-nowrap text-sm font-medium text-gray-500 text-left">
                            <select onchange="updateUserStatus({{ usuario.id }}, this.value)" class="px-3 py-2 border border-gray-300 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300">
                                <option value="1" {% if usuario.is_active %}selected{% endif %}>Ativo</option>
                                <option value="0" {% if not usuario.is_active %}selected{% endif %}>Inativo</option>
                            </select>
                        </td>
                          <td class="px-6 py-2 whitespace-nowrap text-sm font-medium text-gray-500 text-right">
                            <select onchange="handleUserAction({{ usuario.id }}, this.value)" class="px-3 py-2 border border-gray-300 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-800 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300">
                                <option value="">Seleciona uma ação</option>
                                 <option value="{% url 'usuarios:editar_usuario' usuario.id %}">Editar</option>
                                 <option value="{% url 'usuarios:deletar_usuario' usuario.id %}">Excluir</option>
                            </select>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="py-2 px-4 border text-center">Nenhum usuário cadastrado</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
             <div class="my-4 mx-2 flex justify-between items-center">
                    <span class="text-gray-600 text-sm">
                        Página {{ usuarios.number }} de {{ usuarios.paginator.num_pages }}
                    </span>

                    <div class="flex space-x-2">
                        {% if usuarios.has_previous %}
                            <a href="?page=1" class="px-3 py-1 bg-gray-200 rounded">⏮️ Primeira</a>
                            <a href="?page={{ usuarios.previous_page_number }}" class="px-3 py-1 bg-gray-200 rounded">⬅️ Anterior</a>
                        {% endif %}

                        {% if usuarios.has_next %}
                            <a href="?page={{ usuarios.next_page_number }}" class="px-3 py-1 bg-gray-200 rounded">Próxima ➡️</a>
                            <a href="?page={{ usuarios.paginator.num_pages }}" class="px-3 py-1 bg-gray-200 rounded">Última ⏭️</a>
                        {% endif %}
                    </div>
                </div>
         </div>
        </div>
                
    </div>               
 {% comment %} </div>        {% endcomment %}
</main>

{% endblock content %}

usuarios/templates/dashboard/user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h3>Painel do usuário</h3>
    <p>Bem-vindo, {{ user.username }}!</p>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>
      Tipo: {% if user.is_staff or user.is_superuser %}Admin{% else %}Usuário
      Normal{% endif %}
    </p>
  </body>
</html>