app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('usuarios.urls')),
    path('xlsmaker/', include('xlsmaker.urls')),
    path('admin/', admin.site.urls),
     
   
]

usuarios/urls.py
from django.urls import path
from .import views
app_name = 'usuarios' 
urlpatterns = [
    path('', views.login_view, name='user_login' ),
    path('register/', views.register_view, name='register' ),    
    path('plataforma', views.plataforma, name='plataforma'),
    path('user_dashboard', views.user_dashboard, name='user_dashboard'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('solicitacoes/delete/<int:id>/', views.delete_solicitacao, name='delete_solicitacao'),
    path('usuarios', views.listar_usuarios, name='listar_usuarios'),
    path('create/users', views.create_users_view, name='criar_usuarios' ),
    path('update-user-status/', views.update_user_status, name='update_user_status'),
    path('update-user-tokens/', views.update_user_tokens, name='update_user_tokens'),
    path('editar/<int:id>/', views.editar_usuario, name='editar_usuario'),
    path('editar/tokens/<int:id>/', views.editar_tokens, name='editar_tokens'),    
    path('deletar/<int:id>/', views.deletar_usuario, name='deletar_usuario'),
    path('deletar/tokens/<int:id>/', views.deletar_tokens, name='deletar_tokens'),    
    path('dismiss-tutorial/', views.dismiss_tutorial, name='dismiss-tutorial'),
    path('tokens', views.listar_tokens, name='listar_tokens'),
    
]

usuarios/models.py
from django.db import models

usuarios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from xlsmaker.models import Solicitacao 
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
import json
import requests
from xlsmaker.models import UserProfile 
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.db.models import Q


# Função auxiliar para verificar se é admin
def is_admin(user):
    return user.is_authenticated and (user.is_staff or user.is_superuser)

def register_view(request):
    if request.method == 'GET':
        return render(request, 'register.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirma_password = request.POST.get('confirma_password')

        if password != confirma_password:
            messages.error(request, 'As senhas não coincidem!')
            return render(request, 'register.html', {'username': username, 'email': email})
        
        if User.objects.filter(username=username).exists():
            messages.error(request, 'Nome de usuário já está em uso!')
            return render(request, 'register.html', {'email': email})
        
        try:
            user = User.objects.create_user(username=username, email=email, password=password)
            user.is_active = False
            user.save()
            messages.success(request, 'Cadastro realizado com sucesso! Faça seu login.')
            return redirect('usuarios:user_login')
        except Exception as e:
            messages.error(request, f'Erro ao criar usuário: {str(e)}')
            return render(request, 'register.html')


def login_view(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    else:
        username = request.POST.get('username').strip()
        password = request.POST.get('password').strip()
        user = authenticate(username=username, password=password)
        
        if user is not None:
            if not user.is_active:
                messages.error(request, '❌ Sua conta está desativada. Entre em contato com o suporte.')
                return render(request, 'login.html')
            # Resetar tutorial para novos logins
            request.session['show_tutorial'] = True
            request.session['tutorial_dismissed'] = False  
         
            login(request, user)
            if is_admin(user):
                return redirect('usuarios:admin_dashboard')
            else:
                # Criar um perfil automaticamente se ainda não existir
                user_profile, created = UserProfile.objects.get_or_create(user=user, defaults={'tokens_atribuidos': 1000, 'tokens_gastos': 0})         
                return redirect('xlsmaker:dashboard') 
        else:
            messages.error(request, '❌ Erro: email ou senha inválidos!')
            return render(request, 'login.html')

@login_required
def logout_view(request):
    logout(request)
    messages.success(request, 'Logout realizado com sucesso!')
    return redirect('login')

# Painéis de controle
@login_required
def user_dashboard(request):
    context = {'user': request.user}
    return render(request, 'dashboard/user.html', context)

@login_required
@user_passes_test(is_admin, login_url='/auth/login/')
def admin_dashboard(request):    
    query = request.GET.get('q', '')
    solicitacoes_list = Solicitacao.objects.all().order_by('-created_at')
    if query:
        solicitacoes_list = solicitacoes_list.filter(
            Q(nome__icontains=query) | Q(email__icontains=query) | Q(created_at__icontains=query)
        )
    paginator = Paginator(solicitacoes_list, 10)    
    page_number = request.GET.get('page') 
    solicitacoes = paginator.get_page(page_number)     
    context = {'solicitacoes': solicitacoes} 
      # Se for uma requisição AJAX, retorna o HTML parcial
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_users_solicitacoes.html', context)
        return JsonResponse({'html': html})
    return render(request, 'dashboard/admin.html', context)


# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_usuarios(request):
#     usuarios_list = User.objects.all().order_by('-date_joined') 
#     paginator = Paginator(usuarios_list, 10)    
#     page_number = request.GET.get('page')  
#     usuarios = paginator.get_page(page_number) 
#     context = {'usuarios': usuarios}
#     return render(request, 'dashboard/list_users.html', context)

@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def listar_usuarios(request):
    query = request.GET.get('q', '')
    usuarios_list = User.objects.all().order_by('-date_joined')

    if query:
        usuarios_list = usuarios_list.filter(
            Q(username__icontains=query) | Q(email__icontains=query)
        )

    paginator = Paginator(usuarios_list, 10)
    page_number = request.GET.get('page')
    usuarios = paginator.get_page(page_number)

    # Se for uma requisição AJAX, retorna o HTML parcial
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_users_table.html', {'usuarios': usuarios})
        return JsonResponse({'html': html})

    return render(request, 'dashboard/list_users.html', {'usuarios': usuarios})

# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_tokens(request):
#     query = request.GET.get('q', '')
#     user_profile_list = UserProfile.objects.select_related('user').all()
#     if query:
#       user_profile_list = user_profile_list.filter(
#             Q(user__username__icontains=query) | Q(user__email__icontains=query)
#     )
#     for profile in user_profile_list:
#         profile.saldo_tokens = profile.tokens_atribuidos - profile.tokens_gastos
#     paginator = Paginator(user_profile_list, 10)    
#     page_number = request.GET.get('page')  
#     user_profile = paginator.get_page(page_number) 
#     context = {'user_profile': user_profile}
    
#      # Se for uma requisição AJAX, retorna o HTML parcial
#     if request.headers.get('x-requested-with') == 'XMLHttpRequest':
#         html = render_to_string('dashboard/partials/_users_tokens.html', context)
#         return JsonResponse({'html': html})
    
#     return render(request, 'dashboard/list_tokens.html', context)
# @login_required
# @user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
# def listar_tokens(request):

#     query = request.GET.get('q', '')
#     user_profile_list = UserProfile.objects.select_related('user').all()

#     if query:
#         user_profile_list = user_profile_list.filter(
#             Q(user__username__icontains=query) |
#             Q(user__email__icontains=query) |
#             Q(tokens_atribuidos__icontains=query)            
#         )

#     # Calcula saldo_tokens dinamicamente
#     for profile in user_profile_list:
#         profile.saldo_tokens = profile.tokens_atribuidos - profile.tokens_gastos

#     paginator = Paginator(user_profile_list, 10)
#     page_number = request.GET.get('page')
#     user_profile = paginator.get_page(page_number)

#     context = {'user_profile': user_profile}

#     if request.headers.get('x-requested-with') == 'XMLHttpRequest':
#         html = render_to_string('dashboard/partials/_users_tokens.html', context)
#         return JsonResponse({'html': html})

#     return render(request, 'dashboard/list_tokens.html', context)

@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def listar_tokens(request):
    query = request.GET.get('q', '')
    user_profile_list = UserProfile.objects.select_related('user').all().order_by('user__username')

    if query:
        # Filtra por texto (username ou email) OU por número exato de tokens
        try:
            query_as_int = int(query)
            user_profile_list = user_profile_list.filter(
                Q(user__username__icontains=query) |
                Q(user__email__icontains=query) |
                Q(tokens_atribuidos=query_as_int)
            )
        except ValueError:
            # Se não for um número, filtra apenas por texto
            user_profile_list = user_profile_list.filter(
                Q(user__username__icontains=query) |
                Q(user__email__icontains=query)
            )

    paginator = Paginator(user_profile_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'user_profile': page_obj,
        'query': query  # Passa a query para manter na paginação
    }

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        html = render_to_string('dashboard/partials/_user_tokens.html', context)
        return JsonResponse({
            'html': html
        })

    return render(request, 'dashboard/list_tokens.html', context)


@login_required
@user_passes_test(is_admin, login_url=reverse_lazy('usuarios:user_login'))
def create_users_view(request):
    if request.method == 'GET':
        return render(request, 'dashboard/create.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirma_password = request.POST.get('confirma_password')

        if password != confirma_password:

usuarios/templates/login.html
<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-100">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="h-full">
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
      <div class="sm:mx-auto sm:w-full sm:max-w-sm">
        <img
          class="mx-auto h-10 w-auto"
          src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=emerald&shade=600"
          alt="Your Company"
        />
        <h2 class="mt-6 text-center text-2xl font-bold tracking-tight text-gray-900">
          Faça login na sua conta
        </h2>
      </div>

      <!-- CARD -->
      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        <div class="bg-white px-8 py-8 shadow-xl rounded-sm ring-1 ring-gray-200">
          <form class="space-y-6" action="{% url 'usuarios:user_login' %}" method="POST">
            {% csrf_token %}
            <div>
              <label for="username" class="block text-sm font-medium text-gray-900">Username</label>
              <div class="mt-2">
                <input
                  type="text"
                  id="username"
                  name="username"
                  required
                  class="w-full px-3 py-2 bg-gray-100 border border-gray-300 focus:border-emerald-600 focus:ring-2 focus:bg-white focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                  placeholder="Digite o username" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o username'"
                />
              </div>
            </div>

            <div>
              <div class="flex items-center justify-between">
                <label for="password" class="block text-sm font-medium text-gray-900">Password</label>
                <div class="text-sm">
                  <a href="#" class="font-normal text-gray-500 hover:underline hover:text-emerald-500">Esqueceu password?</a>
                </div>
              </div>
            
              <div class="mt-2 relative">
                <input
                  type="password"
                  id="password"
                  name="password"
                  required
                  class="w-full bg-gray-50 px-3 py-2 border border-gray-300 focus:bg-white focus:border-emerald-600 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300 pr-10"
                  placeholder="Digite o password"
                  onfocus="this.placeholder=''" onblur="this.placeholder='Digite o password'"
                />
                <button
                  type="button"
                  onclick="togglePassword()"
                  class="absolute inset-y-0 right-2 flex items-center text-gray-500 hover:text-emerald-600"
                  tabindex="-1"
                >
                  <svg id="eyeIcon" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none"
                    viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                      d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                  </svg>
                </button>
              </div>
              
            </div>

            <div>
              <button
                type="submit"
                class="w-full px-4 py-2 text-white bg-emerald-500 rounded hover:bg-emerald-700 focus:outline-none"
              >
                Entrar
              </button>
            </div>
          </form>

          <p class="mt-6 text-center text-sm text-gray-500">
            Ainda não possui conta?
            <a href="#" class="font-normal text-gray-500 hover:underline hover:text-emerald-500">
              Cria a sua conta aqui
            </a>
          </p>
        </div>

        <!-- Mensagens -->
        {% if messages %}
        <div class="fixed top-4 right-4 space-y-2 z-50">
          {% for message in messages %}
          <div
            id="message-{{ forloop.counter }}"
            class="relative {% if message.tags == 'success' %}bg-green-100 text-green-800{% else %}bg-red-100 text-red-800{% endif %} px-4 py-3 rounded-lg shadow-lg transition-opacity duration-300"
            x-data="{ show: true }"
            x-show="show"
            x-init="setTimeout(() => show = false, 5000)"
          >
            <span>{{ message }}</span>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>

    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script>
      function togglePassword() {
        const passwordInput = document.getElementById('password');
        const eyeIcon = document.getElementById('eyeIcon');
    
        if (passwordInput.type === 'password') {
          passwordInput.type = 'text';
          eyeIcon.innerHTML = `
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.542-7a10.05 10.05 0 011.82-3.043m2.498-2.497A9.956 9.956 0 0112 5c4.478 0 8.268 2.943 9.542 7a9.956 9.956 0 01-4.065 5.226M15 12a3 3 0 00-3-3m0 0a3 3 0 00-3 3m3-3l8 8m-8-8L4 20" />
          `;
        } else {
          passwordInput.type = 'password';
          eyeIcon.innerHTML = `
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
          `;
        }
      }
    </script>
    
  </body>
</html>

usuarios/templates/register.html
<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-50">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body class="h-full">
    <div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
      <div class="sm:mx-auto sm:w-full sm:max-w-sm">
        <img
          class="mx-auto h-10 w-auto"
          src="https://tailwindcss.com/plus-assets/img/logos/mark.svg?color=emerald&shade=600"
          alt="Your Company"
        />
        <h2
          class="mt-10 text-center text-2xl/9 font-bold tracking-tight text-gray-900"
        >
          Cria a sua conta
        </h2>
      </div>

      <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
        <form class="space-y-6" action="{% url 'usuarios:register' %}" method="POST">
              {% csrf_token %}
          <div>
            <label for="email" class="block text-sm/6 font-medium text-gray-900"
              >Username</label
            >
            <div class="mt-2">           
              <input
                type="text"
                id="username"
                name="username"
                required
                class="w-full px-3 py-2 border border-gray-300 focus:border-emerald-100 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Digite o username" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o username'"
              />
            </div>
          </div>

           <div>
            <label for="email" class="block text-sm/6 font-medium text-gray-900"
              >Email</label
            >
            <div class="mt-2">           
              <input
                type="email"
                id="email"
                name="email"
                required
                class="w-full px-3 py-2 border border-gray-300 focus:border-emerald-100 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Digite o email" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o email'"
              />
            </div>
          </div>       

          <div>
               <label for="password" class="block text-sm/6 font-medium text-gray-900"
              >Password</label
            >
            <div class="mt-2">
           
              <input
                type="password"
                id="password"
                name="password"
                required
                class="w-full px-3 py-2 border border-gray-300 focus:border-emerald-100 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Digite o password" onfocus="this.placeholder=''" onblur="this.placeholder='Digite o password'"
              />
            </div>
          </div>

            <div>
               <label for="confirma_password" class="block text-sm/6 font-medium text-gray-900"
              >Confirma password</label
            >
            <div class="mt-2">
           
              <input
                type="password"
                id="confirma_password"
                name="confirma_password"
                required
                class="w-full px-3 py-2 border border-gray-300 focus:border-emerald-100 focus:ring-2 focus:ring-emerald-400 focus:ring-opacity-20 placeholder:text-gray-600 text-gray-800 rounded focus:outline-none transition ease-in-out duration-300"
                placeholder="Confirma o password" onfocus="this.placeholder=''" onblur="this.placeholder='Confirma o password'"
              />
            </div>
          </div>

          <div>            
            <button
              type="submit"
              class="w-full px-4 py-2 text-white bg-emerald-500 rounded hover:bg-emerald-700 focus:outline-none"
            >
              Criar conta
            </button>
          </div>
        </form>

        <p class="mt-10 text-center text-sm/6 text-gray-500">
          Já possui conta?
          <a
            href="{% url 'usuarios:user_login' %}"
            class="font-semibold text-emerald-600 hover:text-emerald-500"
            >Faça login na sua conta aqui</a
          >
        </p>
          <!-- Mensagens -->
        {% if messages %}
        <div class="fixed top-4 right-4 space-y-2 z-50">
            {% for message in messages %}
            <div id="message-{{ forloop.counter }}" 
                class="relative {% if message.tags == 'success' %}bg-green-100 text-green-800{% else %}bg-red-100 text-red-800{% endif %} px-4 py-3 rounded-lg shadow-lg transition-opacity duration-300"
                x-data="{ show: true }"
                x-show="show"
                x-init="setTimeout(() => show = false, 5000)"
               >
                
                <!-- Mensagem-->
                <span>{{ message }}</span>
              
            </div>
            {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </body>
</html>